[phases.setup]
nixPkgs = ["nodejs", "nodePackages.npm"]

[phases.build]
cmds = ["npm install", "npm run build"]

[static]

directory = "dist"
fallback = "index.html"

[variables]
NODE_ENV = "production"