[phases.setup]
nixPkgs = ["nodejs", "nodePackages.npm"]

[phases.build]
# Instalamos y compilamos forzando a Vite
cmds = ["npm install", "npx vite build"]

[static]
# ESTA ES LA CLAVE: Si esto no apunta a "dist", verás el error de MIME type
directory = "dist"
fallback = "index.html"

[variables]
NODE_ENV = "production"